// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHLYwyilR6Lg3z8UFrwPNdgsZ-0mWtaHM',
    appId: '1:731059652063:web:8c591a4657c22bfbfb706a',
    messagingSenderId: '731059652063',
    projectId: 'warmindo-api-70927',
    authDomain: 'warmindo-api-70927.firebaseapp.com',
    storageBucket: 'warmindo-api-70927.appspot.com',
    measurementId: 'G-0BN1SDRVQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEazuDf2zVJ3q2ync7BnOKUfp6pkvab5k',
    appId: '1:731059652063:android:d203b9b567705b16fb706a',
    messagingSenderId: '731059652063',
    projectId: 'warmindo-api-70927',
    storageBucket: 'warmindo-api-70927.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbWmHJo7XP1qgwE2WPQtr0L59VITWhtoc',
    appId: '1:731059652063:ios:bef287b34d6e89b9fb706a',
    messagingSenderId: '731059652063',
    projectId: 'warmindo-api-70927',
    storageBucket: 'warmindo-api-70927.appspot.com',
    iosBundleId: 'com.example.warmindoUserUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbWmHJo7XP1qgwE2WPQtr0L59VITWhtoc',
    appId: '1:731059652063:ios:bef287b34d6e89b9fb706a',
    messagingSenderId: '731059652063',
    projectId: 'warmindo-api-70927',
    storageBucket: 'warmindo-api-70927.appspot.com',
    iosBundleId: 'com.example.warmindoUserUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHLYwyilR6Lg3z8UFrwPNdgsZ-0mWtaHM',
    appId: '1:731059652063:web:f1ea5eacb44a0e0cfb706a',
    messagingSenderId: '731059652063',
    projectId: 'warmindo-api-70927',
    authDomain: 'warmindo-api-70927.firebaseapp.com',
    storageBucket: 'warmindo-api-70927.appspot.com',
    measurementId: 'G-YY28HS5HG6',
  );
}
